output: data/experiment-1
data: data/hendrik.csv
vectorizers:
  - data/experiment-1/tfidf.pkl
  - data/experiment-1/doc2vec.pkl
folds: 5
distributions:
  - type: GMM
    n_components: 5
    covariance_type: full
    # n_iter: 500
    # verbose: 1
  - type: MultinomialNB
    percentile_threshold: 0
    bins: 5
placements:
  - type: CoSim
    n_nearest: 10
