output: data/experiment-1
data: data/hendrik.csv
vectorizers:
  - data/experiment-1/tfidf.pkl
  - data/experiment-1/doc2vec.pkl
folds: 10
distributions:
  - type: GMM
    n_components: 10
    covariance_type: full
  - type: MultinomialNB
    percentile_threshold: 1
    bins: 10
  - type: NearestNeighbors
    neighbors: 10
