data: data/hendrik.csv
vectorizer: data/experiment-1/tfidf/vectorizer.pkl
output: data/experiment-1
folds: 2
distributions:
- type: GMM
  n_components: 5
  n_iter: 500
- type: MultinomialNB
  percentile_threshold: 0
  bins: 2
