type: dict
mapping:
  directory:
    type: str
  uuids:
    type: str
  embeddings:
    type: list
    elements:
      type: str
  users:
    type: str
  folds:
    type: int
  distributions:
    type: list
    elements:
      type: Step
      module: semantic.step
